trigger:
  branches:
    include:
    - '*'
jobs:

- job: Job_1
  displayName: requirements_and_precommit
  # pool:
  #   name: Azure Pipelines
  #   demands: SpecialSoftware # exists check for SpecialSoftware
  variables:
    PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

  steps:
  # found debug solution on this page:
  # https://stackoverflow.com/questions/61271364/fail-to-active-conda-in-azure-devops-pipeline
  # TODO: see if it is possible to retrieve the conda_env name on the fly
  - task: Bash@3
    inputs:
      targetType: 'inline'
      failOnStderr: true
      script: |
        echo "##vso[task.prependpath]$CONDA/bin"
        conda env create -f environment.yml --force
        eval "$(conda shell.bash hook)"
        conda activate {{ cookiecutter.conda_env }}
        conda env list
        pre-commit install
        pre-commit run -a
        conda activate base
        conda env remove --name {{ cookiecutter.conda_env }}
        conda clean --all -y
        pip cache purge
    displayName: 'Install dependencies & Run pre-commits'
